// Wayname — street-view quiz data
// Each city has questions[], name, region (ES), region_en (EN), flag, id.
// Add more cities here to unlock them on the home screen.

const CITIES = [
  {
    id: 'jerez',
    name: 'Jerez de la Frontera',
    region:    'Cádiz, España',
    region_en: 'Cádiz, Spain',
    flag: '🍷',
    questions: [
      { slug: 'plaza-del-arenal',                  name: 'Plaza del Arenal' },
      { slug: 'calle-larga',                        name: 'Calle Larga' },
      { slug: 'plaza-del-mercado',                  name: 'Plaza del Mercado' },
      { slug: 'plaza-san-marcos',                   name: 'Plaza San Marcos' },
      { slug: 'calle-francos',                      name: 'Calle Francos' },
      { slug: 'calle-dona-blanca',                  name: 'Calle Doña Blanca' },
      { slug: 'calle-bodegas',                      name: 'Calle Bodegas' },
      { slug: 'calle-evora',                        name: 'Calle Évora' },
      { slug: 'calle-parque-de-bomberos',           name: 'Calle Parque de Bomberos' },
      { slug: 'paseo-nuevo',                        name: 'Paseo Nuevo' },
      { slug: 'plaza-del-progreso',                 name: 'Plaza del Progreso' },
      { slug: 'plaza-de-cataluna',                  name: 'Plaza de Cataluña' },
      { slug: 'plaza-salvador-allende',             name: 'Plaza Salvador Allende' },
      { slug: 'plaza-alfonso-sanchez-ferrajon',     name: 'Plaza Alfonso Sánchez Ferrajón' },
      { slug: 'calle-doctor-santiago-ramon-y-cajal',name: 'Calle Doctor Santiago Ramón y Cajal' },
      { slug: 'calle-marques-de-bonanza',           name: 'Calle Marqués de Bonanza' },
      { slug: 'calle-puerto-de-las-palomas',        name: 'Calle Puerto de las Palomas' },
      { slug: 'calle-valdepajuelas',                name: 'Calle Valdepajuelas' },
      { slug: 'avenida-chema-rodriguez',            name: 'Avenida Chema Rodríguez' },
      { slug: 'avenida-alcalde-cantos-ropero',      name: 'Avenida Alcalde Cantos Ropero' },
    ],
  },
  {
    id: 'sevilla',
    name: 'Sevilla',
    region:    'Sevilla, España',
    region_en: 'Seville, Spain',
    flag: '🌸',
    questions: [
      { slug: 'sev-calle-san-fernando',                        name: 'Calle San Fernando' },
      { slug: 'sev-muelle-de-la-sal',                          name: 'Muelle de la Sal' },
      { slug: 'sev-paseo-de-catalina-de-ribera',               name: 'Paseo de Catalina de Ribera' },
      { slug: 'sev-paseo-de-cristina',                         name: 'Paseo de Cristina' },
      { slug: 'sev-calle-san-jacinto',                         name: 'Calle San Jacinto' },
      { slug: 'sev-patio-de-banderas',                         name: 'Patio de Banderas' },
      { slug: 'sev-calle-valladares',                          name: 'Calle Valladares' },
      { slug: 'sev-calle-ben-salh-de-sevilla',                 name: 'Calle Ben Salh de Sevilla' },
      { slug: 'sev-calle-alcalde-isacio-contreras',            name: 'Calle Alcalde Isacio Contreras' },
      { slug: 'sev-avenida-isabel-la-catolica',                name: 'Avenida Isabel la Católica' },
      { slug: 'sev-plaza-de-america',                          name: 'Plaza de América' },
      { slug: 'sev-avenida-conde-de-urbina',                   name: 'Avenida Conde de Urbina' },
      { slug: 'sev-plaza-de-la-gavidia',                       name: 'Plaza de la Gavidia' },
      { slug: 'sev-glorieta-rafael-torres',                    name: 'Glorieta Rafael Torres' },
      { slug: 'sev-calle-fray-ceferino-gonzalez',              name: 'Calle Fray Ceferino González' },
      { slug: 'sev-callejon-del-agua',                         name: 'Callejón del Agua' },
      { slug: 'sev-calle-asuncion',                            name: 'Calle Asunción' },
      { slug: 'sev-avenida-pizarro',                           name: 'Avenida Pizarro' },
      { slug: 'sev-avenida-hernan-cortes',                     name: 'Avenida Hernán Cortés' },
      { slug: 'sev-patio-de-la-diputacion',                    name: 'Patio de la Diputación' },
    ],
  },
  {
    id: 'cadiz',
    name: 'Cádiz',
    region:    'Cádiz, España',
    region_en: 'Cádiz, Spain',
    flag: '⚓',
    questions: [
      { slug: 'cad-plaza-de-espana',                           name: 'Plaza de España' },
      { slug: 'cad-plaza-cigarrera-micaela-de-castro',         name: 'Plaza Cigarrera Micaela de Castro' },
      { slug: 'cad-calle-sacramento',                          name: 'Calle Sacramento' },
      { slug: 'cad-calle-virgen-de-la-palma',                  name: 'Calle Virgen de la Palma' },
      { slug: 'cad-calle-libertad',                            name: 'Calle Libertad' },
      { slug: 'cad-calle-fernando-el-catolico',                name: 'Calle Fernando el Católico' },
      { slug: 'cad-plaza-manolo-santander',                    name: 'Plaza Manolo Santander' },
      { slug: 'cad-calle-abreu',                               name: 'Calle Abreu' },
      { slug: 'cad-calle-santo-domingo',                       name: 'Calle Santo Domingo' },
      { slug: 'cad-calle-de-ecuador',                          name: 'Calle de Ecuador' },
      { slug: 'cad-calle-del-meson',                           name: 'Calle del Mesón' },
      { slug: 'cad-calle-zorrilla',                            name: 'Calle Zorrilla' },
      { slug: 'cad-calle-novena',                              name: 'Calle Novena' },
      { slug: 'cad-calle-mirador',                             name: 'Calle Mirador' },
      { slug: 'cad-calle-ustariz',                             name: 'Calle Ustariz' },
      { slug: 'cad-calle-viento',                              name: 'Calle Viento' },
      { slug: 'cad-plaza-de-san-juan-de-dios',                 name: 'Plaza de San Juan de Dios' },
      { slug: 'cad-calle-pelota',                              name: 'Calle Pelota' },
      { slug: 'cad-plaza-viudas',                              name: 'Plaza Viudas' },
      { slug: 'cad-calle-porteria-de-capuchinos',              name: 'Calle Portería de Capuchinos' },
    ],
  },

  {
    id: 'madrid',
    name: 'Madrid',
    region:    'Madrid, España',
    region_en: 'Madrid, Spain',
    flag: '👑',
    questions: [
      { slug: 'mad-paseo-de-los-platanos',                         name: 'Paseo de los Plátanos' },
      { slug: 'mad-calle-del-carmen',                              name: 'Calle del Carmen' },
      { slug: 'mad-plaza-de-la-armeria',                           name: 'Plaza de la Armería' },
      { slug: 'mad-plaza-de-santo-domingo',                        name: 'Plaza de Santo Domingo' },
      { slug: 'mad-plaza-del-angel',                               name: 'Plaza del Ángel' },
      { slug: 'mad-plaza-de-jacinto-benavente',                    name: 'Plaza de Jacinto Benavente' },
      { slug: 'mad-plaza-de-juan-goytisolo',                       name: 'Plaza de Juan Goytisolo' },
      { slug: 'mad-calle-sevilla',                                 name: 'Calle Sevilla' },
      { slug: 'mad-plaza-de-emilio-jimenez-millas',                name: 'Plaza de Emilio Jiménez Millas' },
      { slug: 'mad-plaza-de-san-martin',                           name: 'Plaza de San Martín' },
      { slug: 'mad-calle-de-irun',                                 name: 'Calle de Irún' },
      { slug: 'mad-plaza-de-san-ildefonso',                        name: 'Plaza de San Ildefonso' },
      { slug: 'mad-plaza-santa-barbara',                           name: 'Plaza Santa Bárbara' },
      { slug: 'mad-plaza-de-oriente',                              name: 'Plaza de Oriente' },
      { slug: 'mad-calle-de-garcia-molinas',                       name: 'Calle de García Molinas' },
      { slug: 'mad-plaza-de-santiago',                             name: 'Plaza de Santiago' },
      { slug: 'mad-plaza-de-carlos-cambronero',                    name: 'Plaza de Carlos Cambronero' },
      { slug: 'mad-calle-de-tetuan',                               name: 'Calle de Tetuán' },
      { slug: 'mad-plaza-de-la-villa-de-paris',                    name: 'Plaza de la Villa de París' },
      { slug: 'mad-calle-del-postigo-de-san-martin',               name: 'Calle del Postigo de San Martín' },
    ],
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    region:    'Barcelona, España',
    region_en: 'Barcelona, Spain',
    flag: '🌊',
    questions: [
      { slug: 'bcn-la-rambla',                                     name: 'La Rambla' },
      { slug: 'bcn-moll-de-la-fusta',                              name: 'Moll de la Fusta' },
      { slug: 'bcn-moll-de-la-barceloneta',                        name: 'Moll de la Barceloneta' },
      { slug: 'bcn-avinguda-del-portal-de-l-angel',                name: 'Avinguda del Portal de l\'Àngel' },
      { slug: 'bcn-rambla-del-raval',                              name: 'Rambla del Raval' },
      { slug: 'bcn-pla-de-miquel-tarradell',                       name: 'Pla de Miquel Tarradell' },
      { slug: 'bcn-carrer-de-wellington',                          name: 'Carrer de Wellington' },
      { slug: 'bcn-placa-de-catalunya',                            name: 'Plaça de Catalunya' },
      { slug: 'bcn-gran-via-de-les-corts-catalanes',               name: 'Gran Via de les Corts Catalanes' },
      { slug: 'bcn-carrer-del-marques-de-campo-sagrado',           name: 'Carrer del Marquès de Campo Sagrado' },
      { slug: 'bcn-carrer-comercial',                              name: 'Carrer Comercial' },
      { slug: 'bcn-placa-de-la-universitat',                       name: 'Plaça de la Universitat' },
      { slug: 'bcn-placa-de-la-bella-dorita',                      name: 'Plaça de la Bella Dorita' },
      { slug: 'bcn-passeig-de-lluis-companys',                     name: 'Passeig de Lluís Companys' },
      { slug: 'bcn-placa-de-sant-agusti-vell',                     name: 'Plaça de Sant Agustí Vell' },
      { slug: 'bcn-avinguda-de-la-catedral',                       name: 'Avinguda de la Catedral' },
      { slug: 'bcn-placa-de-sant-agusti',                          name: 'Plaça de Sant Agustí' },
      { slug: 'bcn-placeta-de-ramon-amadeu',                       name: 'Placeta de Ramon Amadeu' },
      { slug: 'bcn-carrer-del-parlament',                          name: 'Carrer del Parlament' },
      { slug: 'bcn-passeig-de-joaquim-renart',                     name: 'Passeig de Joaquim Renart' },
    ],
  },
  {
    id: 'gijon',
    name: 'Gijón',
    region:    'Asturias, España',
    region_en: 'Asturias, Spain',
    flag: '⛵',
    questions: [
      { slug: 'gij-paseo-del-muelle',                              name: 'Paseo del Muelle' },
      { slug: 'gij-muelle-del-fomentin-o-del-carbon',              name: 'Muelle del Fomentín o del Carbón' },
      { slug: 'gij-gr-100-via-de-la-plata',                        name: 'GR 100 Vía de la Plata' },
      { slug: 'gij-plaza-del-instituto',                           name: 'Plaza del Instituto' },
      { slug: 'gij-paseo-de-poniente-fomento',                     name: 'Paseo de Poniente - Fomento' },
      { slug: 'gij-jardines-de-begona',                            name: 'Jardines de Begoña' },
      { slug: 'gij-plaza-de-la-soledad',                           name: 'Plaza de La Soledad' },
      { slug: 'gij-paseo-de-begona',                               name: 'Paseo de Begoña' },
      { slug: 'gij-plazoleta-de-la-actriz-aurora-sanchez',         name: 'Plazoleta de la Actríz Aurora Sánchez' },
      { slug: 'gij-campo-valdes',                                  name: 'Campo Valdés' },
      { slug: 'gij-muelle-victoria-o-el-muellin',                  name: 'Muelle Victoria o El Muellín' },
      { slug: 'gij-plaza-del-humedal',                             name: 'Plaza del Humedal' },
      { slug: 'gij-muelle-del-fomentin',                           name: 'Muelle del Fomentín' },
      { slug: 'gij-plaza-europa',                                  name: 'Plaza Europa' },
      { slug: 'gij-calle-del-agua',                                name: 'Calle del Agua' },
      { slug: 'gij-calle-juanin-de-mieres',                        name: 'Calle Juanín de Mieres' },
      { slug: 'gij-calle-juan-xxiii',                              name: 'Calle Juan XXIII' },
      { slug: 'gij-calle-tomas-zarracina',                         name: 'Calle Tomás Zarracina' },
      { slug: 'gij-calle-asturias',                                name: 'Calle Asturias' },
      { slug: 'gij-calle-fortuna-balnearia',                       name: 'Calle Fortuna Balnearia' },
    ],
  },
];
